# Generated by Django 5.0.1 on 2024-02-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.PositiveIntegerField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
